baseURL = "https://learnwithalka.github.io/"
languageCode = "en-us"
title = "Kajal Dhami"
theme = "KeepIt"

[Permalinks]
 posts = "/:title"

[menu]
  [[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 1

  [[menu.main]]
    name = "Biology"
    url = "/biology/"
    weight = 2

  [[menu.main]]
    name = "Chemistry"
    url = "/chemistry/"
    weight = 3

  [[menu.main]]
    name = "Physics"
    url = "/physics/"
    weight = 4

  [[menu.main]]
    name = "Question Papers"
    url = "/question_papers/"
    weight = 5

  [[menu.main]]
    name = "Recall Notices"
    url = "/recall_notice/"
    weight = 6

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 7

[params.social]
    Youtubecustom = "learnwithalkayadav"
    Instagram = "learnwithalka"
    Facebook = "learnwithalka"
    Telegram = "learnwithalka"

[params.share]
Youtubecustom = true
Telegram = true
Instagram = true
Facebook = true

[author]
  name = "Kumar Vipin Yadav"

avatar = "/images/profile1.png"
home_mode = "post"
relativeURLs = true
canonifyURLs = true
