name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo

      - name: Update Json
        run: python find_video_info.py ${{ secrets.API_KEY_FOR_YT_API }}

      - name: Update files to GitHub Repo
        run: git status; git add .; git config --local user.name "Kumar Vipin Yadav"; git config --local user.email "kumarvipinyadav369@gmail.com"; git commit -m "Updating Json data from $GITHUB_RUN_NUMBER";git push origin main

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public